// The capability checklist and the example pages that cover it.
// The hub (examples/index.html) renders this; test/examples.test.js checks that
// every item is covered by at least one page and every page exists.

/** @type {Array<{ group: string, items: Array<[id: string, label: string]> }>} */
export const checklist = [
  { group: 'HTML modules', items: [
    ['hm.template', '<template export> → HTMLTemplateElement'],
    ['hm.default', 'export="default"'],
    ['hm.style', '<style export> → constructed CSSStyleSheet'],
    ['hm.style-fallback', '<style export> → { kind: "stylesheet", cssText } without CSSStyleSheet'],
    ['hm.json', '<script type="application/json"> and +json exports'],
    ['hm.script-inline', 'inline <script type="module" export> → namespace (data: URL + sourceURL)'],
    ['hm.script-src', '<script type="module" src export>'],
    ['hm.other', 'any other element (e.g. <svg>) exports the element'],
    ['hm.private', 'unexported markup stays private'],
    ['hm.no-doctype', 'modules without a doctype or <html> wrapper'],
    ['hm.namespace', 'namespaces: frozen, null prototype, sorted, [object Module]; createNamespace / exportNames / hasExport'],
    ['hm.parse', 'parseHTMLModule() used directly'],
    ['hm.interpret', 'custom interpret(element, ctx) with defaultExportValue fallback'],
    ['hm.scriptURL', 'dataScriptURL / custom scriptURL for inline scripts'],
  ] },
  { group: 'Re-exports (barrels)', items: [
    ['re.named', 'export { X } from — <module-binding name>'],
    ['re.renamed', 'export { X as Y } from — as='],
    ['re.shorthand', 'single-binding shorthand <module-export name= as=>'],
    ['re.all', 'export * from — all'],
    ['re.namespace', 'export * as ns from — namespace= (includes default)'],
    ['re.native', 'native spelling <export>/<binding>'],
    ['re.js', 're-exporting from a JS module (same binding identity across languages)'],
    ['re.nested', 'barrels of barrels'],
    ['re.star-default', 'export * skips default'],
    ['re.shadow', 'local exports shadow star exports'],
    ['re.ambiguous', 'conflicting star exports are dropped'],
    ['re.diamond', 'shared dependencies (diamonds) are not cycles'],
    ['re.cycle', 'circular re-export rejected (sequential and self)'],
    ['re.cycle-concurrent', 'circular re-export rejected when loaded concurrently'],
  ] },
  { group: 'Declarative imports', items: [
    ['di.named', '<module-binding name>'],
    ['di.alias', 'as= local alias'],
    ['di.default', 'default= import'],
    ['di.namespace', 'namespace= import'],
    ['di.side-effect', 'side-effect-only import'],
    ['di.shorthand', 'single-binding shorthand on <module-import name=>'],
    ['di.native', '<binding> spelling inside an import'],
    ['di.type', 'type="html" / type="js" override'],
    ['di.bare', 'bare specifier resolved through the page import map'],
    ['di.module', 'el.module promise'],
    ['di.bindings', 'el.bindings'],
    ['di.declaration', 'el.declaration / readImportDeclaration()'],
    ['di.events', 'load / error events on <module-import>'],
    ['di.late', 'imports inserted after page load'],
    ['di.scope', 'ModuleScope get / has / whenDeclared / names, scopeFor(document)'],
    ['di.same-value', 're-declaring a local with the same value is allowed'],
    ['di.apply', 'applyImport() used programmatically'],
  ] },
  { group: 'Registration', items: [
    ['reg.element', 'element= on a binding'],
    ['reg.template', 'template export → shadow-stamping element (templateElementClass)'],
    ['reg.class', 'HTMLElement subclass registered as-is'],
    ['reg.multi', 'one export under several tags (subclass for extra names)'],
    ['reg.idempotent', 'same name + same value is a no-op'],
    ['reg.define-before', '<define-element> before its import'],
    ['reg.define-after', '<define-element> after its import'],
    ['reg.define-late', '<define-element> / import inserted later'],
    ['reg.define-alias', 'component= names an alias or default local'],
    ['reg.defined', 'el.defined promise'],
    ['reg.define-events', 'load / error events on <define-element>'],
    ['reg.prefix', 'custom prefix: <esm-import>, <esm-binding>, <esm-define>'],
    ['reg.options', 'defineModuleElements options: registry, scope, loader, window'],
    ['reg.programmatic', 'defineElement / toElementConstructor / templateElementClass'],
  ] },
  { group: 'Stylesheets', items: [
    ['sty.adopt', 'adopt on a binding'],
    ['sty.adopt-shorthand', 'adopt on the <module-import name=> shorthand'],
    ['sty.idempotent', 'adopting the same sheet twice does not duplicate it'],
    ['sty.switch', 'theme switching by swapping adopted sheets'],
    ['sty.shadow', 'sharing one exported sheet with shadow roots'],
    ['sty.fallback', 'adoptStyleSheet with a cssText descriptor or <style> element'],
  ] },
  { group: 'Loader', items: [
    ['ld.load', 'loader.load() for JS and HTML'],
    ['ld.resolve', 'loader.resolve()'],
    ['ld.cache', 'URL cache (loader.cache), one fetch per URL'],
    ['ld.dedupe', 'concurrent loads share one promise'],
    ['ld.evict', 'failed loads are evicted and can be retried'],
    ['ld.events', 'onEvent: resolve / load / error'],
    ['ld.detect', 'format detection: type override → resolution.type → .html/.htm'],
    ['ld.order', 'bare specifiers: importMap → router → hostResolve'],
    ['ld.module-reuse', 'router-provided module reused without re-importing'],
    ['ld.hooks', 'options: fetch, parseHTML, importModule, scriptURL, interpret, detectType, window, baseURL'],
    ['ld.bootstrap', 'src/browser.js one-script bootstrap'],
  ] },
  { group: 'Import maps', items: [
    ['im.exact', 'exact matches'],
    ['im.prefix', 'trailing-slash prefix matches'],
    ['im.longest', 'longest key wins'],
    ['im.scopes', 'scopes by referrer'],
    ['im.url-keys', 'URL keys remap absolute URLs'],
    ['im.unmapped', 'unmapped bare specifiers → null; relative/URL pass through'],
    ['im.merge', 'mergeImportMaps (later wins, scopes merge)'],
    ['im.script', 'importMapScript (escapes "<")'],
    ['im.parse', 'parseURLLikeSpecifier'],
    ['im.compile', 'compileImportMap → import map + lock (with scopes)'],
    ['im.loader-scopes', 'loader importMap scopes apply inside HTML-module re-exports'],
  ] },
  { group: 'Routers', items: [
    ['rt.interface', 'isRouter / toRouter (function returning string, object or null)'],
    ['rt.chain', 'chainRouters: first non-null wins'],
    ['rt.basic', "basicRouter static aliases: '*', '@x/*', 'x*', 'scheme:', exact; specificity"],
    ['rt.basic-fn', 'basicRouter function targets (see the referrer) and array (ordered) routes'],
    ['rt.import-map', 'importMapRouter claims only mapped specifiers'],
    ['rt.type', 'router-supplied type: "html"'],
  ] },
  { group: 'mport v2 routing', items: [
    ['mp.adapter', 'fromMport(createRouter(...)) as a Router'],
    ['mp.specifiers', 'bare, scoped, npm: and jsr: specifiers; ranges resolved through the registry'],
    ['mp.match', 'fromMport match: relative, URL and unknown-scheme specifiers skip mport'],
    ['mp.fallback', 'fallback strategy: a dead mirror is skipped'],
    ['mp.race', 'race strategy: first success wins, losers are aborted'],
    ['mp.adaptive', 'adaptive / weighted strategy reorders by health'],
    ['mp.trace', 'per-resolution trace (lookup, resolved, probe, ok, fail, skip, aborted) on the resolve event'],
    ['mp.health', 'provider health, circuit breaker, router.health.snapshot(), shared health'],
    ['mp.lock', 'lockfile pinning: no registry lookups, build locking'],
    ['mp.verified', 'verified(): SRI hashes in the lock and import map, mismatches rejected'],
    ['mp.signal', 'AbortSignal passes from loader.load() through the router'],
    ['mp.module-reuse', 'probe: "import" → the loader reuses mport\'s evaluated module'],
    ['mp.deprecated', 'deprecated mportRouter() wrapper; basicRouter probing removed'],
    ['mp.live', 'mport v2 routing across real public CDNs'],
  ] },
  { group: 'CLI', items: [
    ['cli.build', 'html-modules build (import map)'],
    ['cli.lock', '--lock writes an mport-format lockfile'],
    ['cli.pin', 'the lockfile is passed back to the config and pins mport (--relock ignores it)'],
    ['cli.html', '--html <script type="importmap">'],
    ['cli.resolve', 'html-modules resolve (--trace)'],
    ['cli.config', 'config: static aliases + fromMport chain, scopes, importMap merge'],
  ] },
  { group: 'Error paths', items: [
    ['err.missing-export', 'missing export → SyntaxError'],
    ['err.missing-reexport', 'missing re-exported name → SyntaxError'],
    ['err.cycle', 'cyclic re-export → Error'],
    ['err.missing-html', 'missing HTML module (404)'],
    ['err.missing-js', 'missing JS module'],
    ['err.non-element', 'registering a non-HTMLElement class → TypeError'],
    ['err.non-constructor', 'registering a non-constructor value → TypeError'],
    ['err.bad-name', 'invalid custom element name → SyntaxError'],
    ['err.redefine', 'tag already defined by a different constructor'],
    ['err.dup-identifier', 'duplicate local binding → SyntaxError'],
    ['err.dup-export', 'duplicate / empty export name in an HTML module'],
    ['err.reexport-shape', 're-export without all / namespace / bindings'],
    ['err.no-loader', 're-export without a loader'],
    ['err.script-type', 'unsupported exported <script type>'],
    ['err.default-alias', 'importing "default" without as='],
    ['err.decl', '<module-import> without from, shorthand without name, binding without name'],
    ['err.define-attrs', '<define-element> without name/component'],
    ['err.never', '<define-element> with a misspelled component waits forever'],
    ['err.adopt', 'adopt on a non-stylesheet'],
    ['err.unresolved', 'unresolvable bare specifier'],
    ['err.prefix-target', 'import map prefix target without trailing "/"'],
    ['err.basic-probe', 'basicRouter with a probe or several targets → migration TypeError'],
    ['err.mport', 'mport: every provider fails → RoutingError with a trace'],
    ['err.mport-resolution', 'mport: impossible version range → ResolutionError'],
    ['err.compile', 'compileImportMap: unresolvable specifier'],
    ['err.to-router', 'toRouter(non-router) → TypeError'],
  ] },
];

/** @type {Array<{ id: string, href: string, title: string, summary: string, offline: boolean, covers: string[] }>} */
export const pages = [
  {
    id: 'quickstart', href: 'quickstart.html', title: 'Quickstart', offline: true,
    summary: 'The one-script bootstrap: a page import map, a barrel, a JS component under two tags, <define-element> before its import, adopt and a namespace import.',
    covers: ['ld.bootstrap', 'di.bare', 'di.named', 'di.alias', 'di.default', 'di.namespace', 'reg.element', 'reg.multi', 'reg.define-before', 'sty.adopt', 're.renamed', 're.all', 're.namespace', 're.js', 'hm.template', 'hm.default', 'hm.json', 'hm.script-inline', 'hm.private', 'di.module'],
  },
  {
    id: 'components', href: 'component-library.html', title: 'Component library in HTML modules', offline: true,
    summary: 'A small design system written as HTML modules: templates with slots and parts, shared tokens, icons as <svg> exports, JSON config, module-script helpers and a barrel that publishes it all.',
    covers: ['hm.template', 'hm.default', 'hm.style', 'hm.json', 'hm.script-inline', 'hm.script-src', 'hm.other', 'hm.private', 'hm.no-doctype', 're.named', 're.renamed', 're.all', 're.namespace', 're.js', 're.nested', 'di.named', 'di.alias', 'di.default', 'di.namespace', 'di.type', 'di.native', 'di.shorthand', 'di.bare', 'reg.element', 'reg.template', 'reg.class', 'sty.adopt', 'sty.adopt-shorthand', 'sty.idempotent', 'di.same-value', 'ld.detect', 'ld.bootstrap'],
  },
  {
    id: 'barrels', href: 'barrels.html', title: 'Nested barrels', offline: true,
    summary: 'Barrels of barrels using every re-export form, with live identity checks for shadowing, ambiguity, default handling and diamonds.',
    covers: ['re.named', 're.renamed', 're.shorthand', 're.all', 're.namespace', 're.native', 're.js', 're.nested', 're.star-default', 're.shadow', 're.ambiguous', 're.diamond', 'hm.namespace', 'ld.load', 'ld.cache', 'ld.dedupe', 'ld.hooks', 'di.namespace', 'di.bindings', 'reg.element', 'reg.template'],
  },
  {
    id: 'registration', href: 'registration.html', title: 'Registration', offline: true,
    summary: 'One class under several tags, templates under two names, <define-element> before, after and late, custom prefixes with an isolated scope, a logging registry and the programmatic API.',
    covers: ['reg.element', 'reg.template', 'reg.class', 'reg.multi', 'reg.idempotent', 'reg.define-before', 'reg.define-after', 'reg.define-late', 'reg.define-alias', 'reg.defined', 'reg.define-events', 'reg.prefix', 'reg.options', 'reg.programmatic', 'di.late', 'di.events', 'di.module', 'di.bindings', 'di.declaration', 'di.scope', 'di.same-value', 'di.side-effect', 'di.apply', 'err.never'],
  },
  {
    id: 'theming', href: 'theming.html', title: 'Adopted stylesheets and theming', offline: true,
    summary: 'Themes as <style export> sheets: adopt, switch, share with shadow roots, and the cssText fallback path.',
    covers: ['hm.style', 'hm.style-fallback', 'sty.adopt', 'sty.adopt-shorthand', 'sty.idempotent', 'sty.switch', 'sty.shadow', 'sty.fallback', 'reg.template', 'di.scope', 'ld.hooks', 'ld.bootstrap'],
  },
  {
    id: 'import-maps', href: 'import-maps.html', title: 'Import-map playground', offline: true,
    summary: 'Edit maps and see resolution live: exact, prefix, longest match, scopes, URL keys, merging, serialization, and loader scopes inside HTML-module re-exports.',
    covers: ['im.exact', 'im.prefix', 'im.longest', 'im.scopes', 'im.url-keys', 'im.unmapped', 'im.merge', 'im.script', 'im.parse', 'im.compile', 'im.loader-scopes', 'ld.order', 'ld.resolve', 'ld.events', 'mp.adapter', 'mp.specifiers', 'err.prefix-target', 'err.unresolved'],
  },
  {
    id: 'routers', href: 'routers.html', title: 'Routing with mport', offline: true,
    summary: 'A traced router chain ending in fromMport(createRouter(...)): npm:/jsr: ranges, fallback, race and adaptive strategies, health and circuit breaking, lockfile pinning and integrity, all against local mirrors.',
    covers: ['rt.interface', 'rt.chain', 'rt.basic', 'rt.basic-fn', 'rt.import-map', 'rt.type', 'mp.adapter', 'mp.specifiers', 'mp.match', 'mp.fallback', 'mp.race', 'mp.adaptive', 'mp.trace', 'mp.health', 'mp.lock', 'mp.verified', 'mp.signal', 'mp.module-reuse', 'mp.deprecated', 'ld.order', 'ld.module-reuse', 'ld.detect', 'im.compile', 'err.basic-probe', 'err.to-router'],
  },
  {
    id: 'timeline', href: 'loader-timeline.html', title: 'Loader events timeline', offline: true,
    summary: 'Every resolve / load / error event on a live timeline, with simulated latency, cache hits, concurrent de-duplication and retry after eviction.',
    covers: ['ld.events', 'ld.load', 'ld.resolve', 'ld.cache', 'ld.dedupe', 'ld.evict', 'ld.hooks', 'di.events', 'di.late', 're.nested'],
  },
  {
    id: 'hooks', href: 'loader-hooks.html', title: 'Loader hooks', offline: true,
    summary: 'A loader over an in-memory file system: custom fetch, parseHTML, importModule, scriptURL, interpret and detectType, plus parseHTMLModule and namespaces by hand.',
    covers: ['ld.hooks', 'ld.detect', 'hm.interpret', 'hm.scriptURL', 'hm.parse', 'hm.namespace', 'hm.json', 'err.no-loader'],
  },
  {
    id: 'errors', href: 'errors.html', title: 'Error cases', offline: true,
    summary: 'Every error path, triggered on purpose and shown on the page with its type and message.',
    covers: ['err.missing-export', 'err.missing-reexport', 'err.cycle', 'err.missing-html', 'err.missing-js', 'err.non-element', 'err.non-constructor', 'err.bad-name', 'err.redefine', 'err.dup-identifier', 'err.dup-export', 'err.reexport-shape', 'err.no-loader', 'err.script-type', 'err.default-alias', 'err.decl', 'err.define-attrs', 'err.never', 'err.adopt', 'err.unresolved', 'err.prefix-target', 'err.basic-probe', 'err.mport', 'err.mport-resolution', 'err.compile', 'err.to-router', 're.cycle', 're.cycle-concurrent', 'ld.evict', 'di.events', 'reg.define-events'],
  },
  {
    id: 'app', href: 'app.html', title: 'Task board app', offline: true,
    summary: 'A small task board built from HTML modules: a component barrel, seed data as JSON, adopted themes, a JS component re-exported through HTML, and a loader status bar.',
    covers: ['hm.template', 'hm.style', 'hm.json', 'hm.script-src', 'hm.other', 'hm.no-doctype', 're.js', 're.renamed', 're.all', 're.namespace', 'di.bare', 'di.namespace', 'di.alias', 'reg.element', 'reg.template', 'reg.class', 'reg.define-after', 'reg.multi', 'sty.adopt', 'sty.switch', 'ld.events', 'ld.hooks'],
  },
  {
    id: 'cli', href: 'cli.html', title: 'Compiled import map (CLI)', offline: true,
    summary: 'An import map and mport-format lockfile produced by `html-modules build` from static aliases chained with mport v2, then used at runtime and fed back to mport to pin versions.',
    covers: ['cli.build', 'cli.lock', 'cli.pin', 'cli.html', 'cli.resolve', 'cli.config', 'im.compile', 'im.scopes', 'rt.import-map', 'rt.basic', 'rt.basic-fn', 'mp.adapter', 'mp.specifiers', 'mp.fallback', 'mp.lock'],
  },
  {
    id: 'cdn', href: 'cdn.html', title: 'Live CDN routing (mport)', offline: false,
    summary: 'npm: and jsr: specifiers routed across public CDNs by mport v2, with each lookup and probe traced and provider health tracked. Needs network access.',
    covers: ['mp.live', 'mp.adapter', 'mp.specifiers', 'mp.race', 'mp.trace', 'mp.health', 'mp.module-reuse', 'rt.chain', 'ld.module-reuse', 'ld.events'],
  },
];

/** Items no page covers, with the reason. */
export const uncovered = {};

export const allItems = checklist.flatMap((g) => g.items.map(([id, label]) => ({ id, label, group: g.group })));
