// The capability checklist and the example pages that cover it.
// The hub (examples/index.html) renders this; test/examples.test.js checks that
// every item is covered by at least one page and every page exists.

/** @type {Array<{ group: string, items: Array<[id: string, label: string]> }>} */
export const checklist = [
  { group: 'HTML modules', items: [
    ['hm.template', '<template export> → HTMLTemplateElement'],
    ['hm.default', 'export="default"'],
    ['hm.style', '<style export> → constructed CSSStyleSheet'],
    ['hm.style-fallback', '<style export> → { kind: "stylesheet", cssText } without CSSStyleSheet'],
    ['hm.json', '<script type="application/json"> and +json exports'],
    ['hm.script-inline', 'inline <script type="module" export> → namespace (data: URL + sourceURL)'],
    ['hm.script-src', '<script type="module" src export>'],
    ['hm.other', 'any other element (e.g. <svg>) exports the element'],
    ['hm.private', 'unexported markup stays private'],
    ['hm.no-doctype', 'modules without a doctype or <html> wrapper'],
    ['hm.namespace', 'namespaces: frozen, null prototype, sorted, [object Module]; createNamespace / exportNames / hasExport'],
    ['hm.parse', 'parseHTMLModule() used directly'],
    ['hm.interpret', 'custom interpret(element, ctx) with defaultExportValue fallback'],
    ['hm.scriptURL', 'dataScriptURL / custom scriptURL for inline scripts'],
  ] },
  { group: 'Re-exports (barrels)', items: [
    ['re.named', 'export { X } from — <module-binding name>'],
    ['re.renamed', 'export { X as Y } from — as='],
    ['re.shorthand', 'single-binding shorthand <module-export name= as=>'],
    ['re.all', 'export * from — all'],
    ['re.namespace', 'export * as ns from — namespace= (includes default)'],
    ['re.native', 'native spelling <export>/<binding>'],
    ['re.js', 're-exporting from a JS module (same binding identity across languages)'],
    ['re.nested', 'barrels of barrels'],
    ['re.star-default', 'export * skips default'],
    ['re.shadow', 'local exports shadow star exports'],
    ['re.ambiguous', 'conflicting star exports are dropped'],
    ['re.diamond', 'shared dependencies (diamonds) are not cycles'],
    ['re.cycle', 'circular re-export rejected (sequential and self)'],
    ['re.cycle-concurrent', 'circular re-export rejected when loaded concurrently'],
  ] },
  { group: 'Declarative imports', items: [
    ['di.named', '<module-binding name>'],
    ['di.alias', 'as= local alias'],
    ['di.default', 'default= import'],
    ['di.namespace', 'namespace= import'],
    ['di.side-effect', 'side-effect-only import'],
    ['di.shorthand', 'single-binding shorthand on <module-import name=>'],
    ['di.native', '<binding> spelling inside an import'],
    ['di.type', 'type="html" / type="js" override'],
    ['di.bare', 'bare specifier resolved through the page import map'],
    ['di.module', 'el.module promise'],
    ['di.bindings', 'el.bindings'],
    ['di.declaration', 'el.declaration / readImportDeclaration()'],
    ['di.events', 'load / error events on <module-import>'],
    ['di.late', 'imports inserted after page load'],
    ['di.scope', 'ModuleScope get / has / whenDeclared / names, scopeFor(document)'],
    ['di.same-value', 're-declaring a local with the same value is allowed'],
    ['di.apply', 'applyImport() used programmatically'],
  ] },
  { group: 'Registration', items: [
    ['reg.element', 'element= on a binding'],
    ['reg.template', 'template export → shadow-stamping element (templateElementClass)'],
    ['reg.class', 'HTMLElement subclass registered as-is'],
    ['reg.multi', 'one export under several tags (subclass for extra names)'],
    ['reg.idempotent', 'same name + same value is a no-op'],
    ['reg.define-before', '<define-element> before its import'],
    ['reg.define-after', '<define-element> after its import'],
    ['reg.define-late', '<define-element> / import inserted later'],
    ['reg.define-alias', 'component= names an alias or default local'],
    ['reg.defined', 'el.defined promise'],
    ['reg.define-events', 'load / error events on <define-element>'],
    ['reg.prefix', 'custom prefix: <esm-import>, <esm-binding>, <esm-define>'],
    ['reg.options', 'defineModuleElements options: registry, scope, loader, window'],
    ['reg.programmatic', 'defineElement / toElementConstructor / templateElementClass'],
  ] },
  { group: 'Stylesheets', items: [
    ['sty.adopt', 'adopt on a binding'],
    ['sty.adopt-shorthand', 'adopt on the <module-import name=> shorthand'],
    ['sty.idempotent', 'adopting the same sheet twice does not duplicate it'],
    ['sty.switch', 'theme switching by swapping adopted sheets'],
    ['sty.shadow', 'sharing one exported sheet with shadow roots'],
    ['sty.fallback', 'adoptStyleSheet with a cssText descriptor or <style> element'],
  ] },
  { group: 'Loader', items: [
    ['ld.load', 'loader.load() for JS and HTML'],
    ['ld.resolve', 'loader.resolve()'],
    ['ld.cache', 'URL cache (loader.cache), one fetch per URL'],
    ['ld.dedupe', 'concurrent loads share one promise'],
    ['ld.evict', 'failed loads are evicted and can be retried'],
    ['ld.events', 'onEvent: resolve / load / error'],
    ['ld.detect', 'format detection: type override → resolution.type → .html/.htm'],
            ['ld.hooks', 'options: fetch, parseHTML, importModule, scriptURL, interpret, detectType, window, baseURL'],
    ['ld.bootstrap', 'src/browser.js one-script bootstrap'],
  ] },
  { group: 'Error paths', items: [
    ['err.missing-export', 'missing export → SyntaxError'],
    ['err.missing-reexport', 'missing re-exported name → SyntaxError'],
    ['err.cycle', 'cyclic re-export → Error'],
    ['err.missing-html', 'missing HTML module (404)'],
    ['err.missing-js', 'missing JS module'],
    ['err.non-element', 'registering a non-HTMLElement class → TypeError'],
    ['err.non-constructor', 'registering a non-constructor value → TypeError'],
    ['err.bad-name', 'invalid custom element name → SyntaxError'],
    ['err.redefine', 'tag already defined by a different constructor'],
    ['err.dup-identifier', 'duplicate local binding → SyntaxError'],
    ['err.dup-export', 'duplicate / empty export name in an HTML module'],
    ['err.reexport-shape', 're-export without all / namespace / bindings'],
    ['err.no-loader', 're-export without a loader'],
    ['err.script-type', 'unsupported exported <script type>'],
    ['err.default-alias', 'importing "default" without as='],
    ['err.decl', '<module-import> without from, shorthand without name, binding without name'],
    ['err.define-attrs', '<define-element> without name/component'],
    ['err.never', '<define-element> with a misspelled component waits forever'],
    ['err.adopt', 'adopt on a non-stylesheet'],
                              ] },
];

/** @type {Array<{ id: string, href: string, title: string, summary: string, offline: boolean, covers: string[] }>} */
export const pages = [
  {
    id: 'quickstart', href: 'quickstart.html', title: 'Quickstart', offline: true,
    summary: 'The one-script bootstrap: a page import map, a barrel, a JS component under two tags, <define-element> before its import, adopt and a namespace import.',
    covers: ['ld.bootstrap', 'di.bare', 'di.named', 'di.alias', 'di.default', 'di.namespace', 'reg.element', 'reg.multi', 'reg.define-before', 'sty.adopt', 're.renamed', 're.all', 're.namespace', 're.js', 'hm.template', 'hm.default', 'hm.json', 'hm.script-inline', 'hm.private', 'di.module'],
  },
  {
    id: 'components', href: 'component-library.html', title: 'Component library in HTML modules', offline: true,
    summary: 'A small design system written as HTML modules: templates with slots and parts, shared tokens, icons as <svg> exports, JSON config, module-script helpers and a barrel that publishes it all.',
    covers: ['hm.template', 'hm.default', 'hm.style', 'hm.json', 'hm.script-inline', 'hm.script-src', 'hm.other', 'hm.private', 'hm.no-doctype', 're.named', 're.renamed', 're.all', 're.namespace', 're.js', 're.nested', 'di.named', 'di.alias', 'di.default', 'di.namespace', 'di.type', 'di.native', 'di.shorthand', 'di.bare', 'reg.element', 'reg.template', 'reg.class', 'sty.adopt', 'sty.adopt-shorthand', 'sty.idempotent', 'di.same-value', 'ld.detect', 'ld.bootstrap'],
  },
  {
    id: 'barrels', href: 'barrels.html', title: 'Nested barrels', offline: true,
    summary: 'Barrels of barrels using every re-export form, with live identity checks for shadowing, ambiguity, default handling and diamonds.',
    covers: ['re.named', 're.renamed', 're.shorthand', 're.all', 're.namespace', 're.native', 're.js', 're.nested', 're.star-default', 're.shadow', 're.ambiguous', 're.diamond', 'hm.namespace', 'ld.load', 'ld.cache', 'ld.dedupe', 'ld.hooks', 'di.namespace', 'di.bindings', 'reg.element', 'reg.template'],
  },
  {
    id: 'registration', href: 'registration.html', title: 'Registration', offline: true,
    summary: 'One class under several tags, templates under two names, <define-element> before, after and late, custom prefixes with an isolated scope, a logging registry and the programmatic API.',
    covers: ['reg.element', 'reg.template', 'reg.class', 'reg.multi', 'reg.idempotent', 'reg.define-before', 'reg.define-after', 'reg.define-late', 'reg.define-alias', 'reg.defined', 'reg.define-events', 'reg.prefix', 'reg.options', 'reg.programmatic', 'di.late', 'di.events', 'di.module', 'di.bindings', 'di.declaration', 'di.scope', 'di.same-value', 'di.side-effect', 'di.apply', 'err.never'],
  },
  {
    id: 'theming', href: 'theming.html', title: 'Adopted stylesheets and theming', offline: true,
    summary: 'Themes as <style export> sheets: adopt, switch, share with shadow roots, and the cssText fallback path.',
    covers: ['hm.style', 'hm.style-fallback', 'sty.adopt', 'sty.adopt-shorthand', 'sty.idempotent', 'sty.switch', 'sty.shadow', 'sty.fallback', 'reg.template', 'di.scope', 'ld.hooks', 'ld.bootstrap'],
  },
  {
    id: 'errors', href: 'errors.html', title: 'Error cases', offline: true,
    summary: 'Every error path, triggered on purpose and shown on the page with its type and message.',
    covers: ['err.missing-export', 'err.missing-reexport', 'err.cycle', 'err.missing-html', 'err.missing-js', 'err.non-element', 'err.non-constructor', 'err.bad-name', 'err.redefine', 'err.dup-identifier', 'err.dup-export', 'err.reexport-shape', 'err.no-loader', 'err.script-type', 'err.default-alias', 'err.decl', 'err.define-attrs', 'err.never', 'err.adopt', 're.cycle', 're.cycle-concurrent', 'ld.evict', 'di.events', 'reg.define-events'],
  },
  {
    id: 'app', href: 'app.html', title: 'Task board app', offline: true,
    summary: 'A small task board built from HTML modules: a component barrel, seed data as JSON, adopted themes, a JS component re-exported through HTML, and a loader status bar.',
    covers: ['hm.template', 'hm.style', 'hm.json', 'hm.script-src', 'hm.other', 'hm.no-doctype', 're.js', 're.renamed', 're.all', 're.namespace', 'di.bare', 'di.namespace', 'di.alias', 'reg.element', 'reg.template', 'reg.class', 'reg.define-after', 'reg.multi', 'sty.adopt', 'sty.switch', 'ld.events', 'ld.hooks'],
  },
];

/** Items no page covers, with the reason. */
export const uncovered = {};

export const allItems = checklist.flatMap((g) => g.items.map(([id, label]) => ({ id, label, group: g.group })));
